volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - demo

networks:
  demo:
    driver: bridge
    name: demo_network